language: java
jdk: openjdk8
deploy:
  provider: heroku
  app: zkejid-spring-boot-demo
  api_key:
    secure: svVXEDvYgqegXMLBfF+rPYlbYEPm/WGF+d33Nl75Id3J/glFQbweR+c2CrcYzcGbP/7u8Tz8AcrH0B2IQ+U67nNCLKkvK2+66BedTDk9txmDCXvtkyWgO4oWyTeD9aNg3JdLdKG66Nx544uwkSy3U33D70kzdVHhLSNaRR7I77nmW4ocV9vEUXkrMUC5l5Ob0+axyIphp9NLU4qKNY7VUdWBP0X045lvPEKUDFx7w78IuCGxso+Anvi/D4Jfi4CosLdCh2cPc7srYBMPV0KlXpw+lWEOnBsAj237FUJPe5z2p6t2h5P0kO1VHwUTsdHLHSjpUefBAAUodoLkp1BSovPXI0KbkcEcUh3+2nYga2mE2HmblY8jRr5PDAWb/GEEWYuD25TG+5E1htf+I56WmAqQxfYjZDRkhqdrB4Pq4HKvBwEVOc0S1kUG68bFTptQM/tMyJkbNWyZtNfq2ZiT1lJKjzdogtRe/fQn+OsBTD4pOYU0AFr0QtnMKi8j0gmQqJdI2/Eu1a6SbR2K9/WJyjGhqGFtie3u+m5CYxM8LaSHFmgaKysv+zqYmTS/LWBg5XkTEppDuMF73g0qdK7YaNo1taUtaau/RvI8Tq8aTTEp8jkoRwo+J4GIF+CtTvFXQeAIkHE22b4Bx7KDVTXmexr8HLK62eHkMjSX1i6njpw=
